// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACQK5XQLpmeeFwB73ycfVxhx269yjAdHU',
    appId: '1:417023558318:web:bcd87925b5a173f386a33f',
    messagingSenderId: '417023558318',
    projectId: 'fir-app-dcb72',
    authDomain: 'fir-app-dcb72.firebaseapp.com',
    storageBucket: 'fir-app-dcb72.firebasestorage.app',
    measurementId: 'G-HK263DJKHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBApSG3XvazgGjfQQ7VYlqxOf-0M9mxvYg',
    appId: '1:417023558318:android:43dd458bcf09293186a33f',
    messagingSenderId: '417023558318',
    projectId: 'fir-app-dcb72',
    storageBucket: 'fir-app-dcb72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA90zjOukFOa9CzT5rqsjr-2JXxbxjxgpo',
    appId: '1:417023558318:ios:5c583da4824a217586a33f',
    messagingSenderId: '417023558318',
    projectId: 'fir-app-dcb72',
    storageBucket: 'fir-app-dcb72.firebasestorage.app',
    iosBundleId: 'com.demo.app.demoApp',
  );
}
